name: gh-test

on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - 
        name: Setup node
        uses: actions/setup-node@v2-beta
      -
        name: Test build project
        run: |
          npm install
          npm run build